python scripts/rsl_rl/play_avdc.py \
  --device=cpu \
  --task Isaac-Lift-Cube-Franka-IK-Rel-v0 \
  --video_ckpt_dir AVDC/results/isaaclab/Lift-Cube-Randomized/ \
  --video_milestone 24 \
  --task_prompt "pos001" \
  --plan_timeout 15 \
  --camera_sensor overhead_camera \
  --save_video \
  --video_length 2000 \
  --video_folder "debug" \
  --diffusion_source images \
  --motion_backend locotrack \
  --locotrack_root "/home/grant-rinehimer/cornell/dl_robotics/avdc_isaaclab/locotrack/locotrack_pytorch" \
  --locotrack_ckpt "/home/grant-rinehimer/cornell/dl_robotics/avdc_isaaclab/locotrack/locotrack_pytorch/ckpt/locotrack_base.ckpt" \
  --locotrack_model_size base \
  --locotrack_query_chunk_size 256 \
  --locotrack_max_points 256 \
  --locotrack_sample_points 512 \
  --locotrack_min_points 32 \
  > debug/log