python scripts/rsl_rl/play_avdc.py \
  --device=cpu \
  --task Isaac-Lift-Cube-UR10-IK-Rel-v0 \
  --video_ckpt_dir AVDC/results/mw \
  --video_milestone 24 \
  --task_prompt "lift_custom" \
  --plan_timeout 15 \
  --camera_sensor overhead_camera \
  --save_video \
  --video_length 2000 \
  --video_folder "debug" \
  --video_ckpt_path "AVDC/results/mw/model-24.pt" > debug/log